# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Mergee.Api.Eeocs do
  @moduledoc """
  API calls for all endpoints tagged `Eeocs`.
  """

  alias Mergee.Connection
  import Mergee.RequestBuilder


  @doc """
  Returns a list of `EEOC` objects.

  ## Parameters

  - connection (Mergee.Connection): Connection to server
  - x_account_token (String.t): Token identifying the end user.
  - opts (KeywordList): [optional] Optional parameters
    - :candidate_id (String.t): If provided, will only return EEOC info for this candidate.
    - :created_after (DateTime.t): If provided, will only return objects created after this datetime.
    - :created_before (DateTime.t): If provided, will only return objects created before this datetime.
    - :cursor (String.t): The pagination cursor value.
    - :expand (String.t): Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
    - :modified_after (DateTime.t): If provided, will only return objects modified after this datetime.
    - :modified_before (DateTime.t): If provided, will only return objects modified before this datetime.
    - :page_size (integer()): Number of results to return per page.
    - :remote_id (String.t): The API provider's ID for the given object.
  ## Returns

  {:ok, %Mergee.Model.PaginatedEeocList{}} on success
  {:error, info} on failure
  """
  @spec eeocs_list(Tesla.Env.client, String.t, keyword()) :: {:ok, Mergee.Model.PaginatedEeocList.t} | {:error, Tesla.Env.t}
  def eeocs_list(connection, x_account_token, opts \\ []) do
    optional_params = %{
      :"candidate_id" => :query,
      :"created_after" => :query,
      :"created_before" => :query,
      :"cursor" => :query,
      :"expand" => :query,
      :"modified_after" => :query,
      :"modified_before" => :query,
      :"page_size" => :query,
      :"remote_id" => :query
    }
    %{}
    |> method(:get)
    |> url("/eeocs")
    |> add_param(:headers, :"X-Account-Token", x_account_token)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %Mergee.Model.PaginatedEeocList{}}
    ])
  end

  @doc """
  Returns an `EEOC` object with the given `id`.

  ## Parameters

  - connection (Mergee.Connection): Connection to server
  - x_account_token (String.t): Token identifying the end user.
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :expand (String.t): Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
  ## Returns

  {:ok, %Mergee.Model.Eeoc{}} on success
  {:error, info} on failure
  """
  @spec eeocs_retrieve(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, Mergee.Model.Eeoc.t} | {:error, Tesla.Env.t}
  def eeocs_retrieve(connection, x_account_token, id, opts \\ []) do
    optional_params = %{
      :"expand" => :query
    }
    %{}
    |> method(:get)
    |> url("/eeocs/#{id}")
    |> add_param(:headers, :"X-Account-Token", x_account_token)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %Mergee.Model.Eeoc{}}
    ])
  end
end
