# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.AccountToken do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"account_token",
    :"integration"
  ]

  @type t :: %__MODULE__{
    :"account_token" => String.t,
    :"integration" => MergeATSClient.Model.AccountIntegration.t
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.AccountToken do
  import MergeATSClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"integration", :struct, MergeATSClient.Model.AccountIntegration, options)
  end
end

