# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.Application do
  @moduledoc """
  # The Application Object ### Description The `Application` object is used to represent an Application for a job position.  ### Usage Example Fetch from the `LIST Applications` endpoint and filter by `ID` to show all applications.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"candidate",
    :"job",
    :"applied_at",
    :"rejected_at",
    :"source",
    :"credited_to",
    :"current_stage",
    :"reject_reason",
    :"remote_data"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"candidate" => String.t | nil,
    :"job" => String.t | nil,
    :"applied_at" => DateTime.t | nil,
    :"rejected_at" => DateTime.t | nil,
    :"source" => String.t | nil,
    :"credited_to" => String.t | nil,
    :"current_stage" => String.t | nil,
    :"reject_reason" => String.t | nil,
    :"remote_data" => [MergeATSClient.Model.RemoteData.t] | nil
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.Application do
  import MergeATSClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"remote_data", :list, MergeATSClient.Model.RemoteData, options)
  end
end

