# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.Attachment do
  @moduledoc """
  # The Attachment Object ### Description The `Attachment` object is used to represent a attachment for a candidate.  ### Usage Example Fetch from the `LIST Attachments` endpoint and view attachments accessible by a company.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"file_name",
    :"file_url",
    :"candidate",
    :"remote_data"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"file_name" => String.t | nil,
    :"file_url" => String.t | nil,
    :"candidate" => String.t | nil,
    :"remote_data" => [RemoteData] | nil
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.Attachment do
  import MergeATSClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"remote_data", :list, MergeATSClient.Model.RemoteData, options)
  end
end

