# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.Attachment do
  @moduledoc """
  # The Attachment Object ### Description The `Attachment` object is used to represent a attachment for a candidate.  ### Usage Example Fetch from the `GET Candidate` endpoint and view their attachments.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"file_name",
    :"file_url"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"file_name" => String.t | nil,
    :"file_url" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.Attachment do
  def decode(value, _options) do
    value
  end
end

