# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.AvailableActions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"available_model_operations"
  ]

  @type t :: %__MODULE__{
    :"available_model_operations" => [ModelOperation] | nil
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.AvailableActions do
  import MergeATSClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"available_model_operations", :list, MergeATSClient.Model.ModelOperation, options)
  end
end

