# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.DataPassthroughRequest do
  @moduledoc """
  # The DataPassthrough Object ### Description The `DataPassthrough` object is used to send information to an otherwise-unsupported third-party endpoint.  ### Usage Example Create a `DataPassthrough` to get team hierarchies from your Rippling integration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"method",
    :"path",
    :"base_url_override",
    :"data",
    :"headers"
  ]

  @type t :: %__MODULE__{
    :"method" => MethodEnum,
    :"path" => String.t,
    :"base_url_override" => String.t | nil,
    :"data" => %{optional(String.t) => AnyType} | nil,
    :"headers" => %{optional(String.t) => AnyType} | nil
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.DataPassthroughRequest do
  import MergeATSClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"method", :struct, MergeATSClient.Model.MethodEnum, options)
    |> deserialize(:"data", :map, MergeATSClient.Model.AnyType, options)
    |> deserialize(:"headers", :map, MergeATSClient.Model.AnyType, options)
  end
end

