# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.JobInterviewStage do
  @moduledoc """
  # The JobInterviewStage Object ### Description The `JobInterviewStage` object is used to represent the stage of an interview  ### Usage Example Fetch from the `LIST JobInterviewStages` endpoint and view the job interview stages used by a company.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"name",
    :"job",
    :"remote_data"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"name" => String.t | nil,
    :"job" => String.t | nil,
    :"remote_data" => [MergeATSClient.Model.RemoteData.t] | nil
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.JobInterviewStage do
  import MergeATSClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"remote_data", :list, MergeATSClient.Model.RemoteData, options)
  end
end

