# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.JobInterviewStage do
  @moduledoc """
  # The JobInterviewStage Object ### Description The `JobInterviewStage` object is used to represent the stage of an interview  ### Usage Example Fetch from the `LIST Applications` endpoint and view the current stage of various applications.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"name",
    :"job"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"name" => String.t | nil,
    :"job" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.JobInterviewStage do
  def decode(value, _options) do
    value
  end
end

