# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.ModelOperation do
  @moduledoc """
  # The ModelOperation Object ### Description The `ModelOperation` object is used to represent the operations that are currently supported for a given model.  ### Usage Example View what operations are supported for the `Candidate` endpoint.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"model_name",
    :"available_operations",
    :"required_post_parameters"
  ]

  @type t :: %__MODULE__{
    :"model_name" => String.t,
    :"available_operations" => [String.t],
    :"required_post_parameters" => [String.t]
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.ModelOperation do
  def decode(value, _options) do
    value
  end
end

