# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.ModelOperation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"model_name",
    :"available_operations"
  ]

  @type t :: %__MODULE__{
    :"model_name" => String.t,
    :"available_operations" => [String.t]
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.ModelOperation do
  def decode(value, _options) do
    value
  end
end

