# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.Offer do
  @moduledoc """
  # The Offer Object ### Description The `Offer` object is used to represent an offer for an application.  ### Usage Example Fetch from the `LIST Offers` endpoint and filter by `ID` to show all offers.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"application",
    :"creator",
    :"remote_created_at",
    :"closed_at",
    :"sent_at",
    :"start_date",
    :"status",
    :"remote_data"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"application" => String.t | nil,
    :"creator" => String.t | nil,
    :"remote_created_at" => DateTime.t | nil,
    :"closed_at" => DateTime.t | nil,
    :"sent_at" => DateTime.t | nil,
    :"start_date" => DateTime.t | nil,
    :"status" => OfferStatusEnum | nil,
    :"remote_data" => [RemoteData] | nil
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.Offer do
  import MergeATSClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"status", :struct, MergeATSClient.Model.OfferStatusEnum, options)
    |> deserialize(:"remote_data", :list, MergeATSClient.Model.RemoteData, options)
  end
end

