# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.RemoteKey do
  @moduledoc """
  # The RemoteResponse Object ### Description The `RemoteResponse` object is used to represent information returned from a third-party endpoint.  ### Usage Example View the `RemoteResponse` returned from your `DataPassthrough`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"key"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"key" => String.t
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.RemoteKey do
  def decode(value, _options) do
    value
  end
end

