# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.Scorecard do
  @moduledoc """
  # The Scorecard Object ### Description The `Scorecard` object is used to represent a Scorecard for an interview  ### Usage Example Fetch from the `LIST Scorecards` endpoint and filter by `application` to show all scorecard for an applicant.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"application",
    :"interview",
    :"interviewer",
    :"remote_created_at",
    :"submitted_at",
    :"overall_recommendation",
    :"remote_data"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"application" => String.t | nil,
    :"interview" => String.t | nil,
    :"interviewer" => String.t | nil,
    :"remote_created_at" => DateTime.t | nil,
    :"submitted_at" => DateTime.t | nil,
    :"overall_recommendation" => OverallRecommendationEnum | nil,
    :"remote_data" => [RemoteData] | nil
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.Scorecard do
  import MergeATSClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"overall_recommendation", :struct, MergeATSClient.Model.OverallRecommendationEnum, options)
    |> deserialize(:"remote_data", :list, MergeATSClient.Model.RemoteData, options)
  end
end

