# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.SyncStatus do
  @moduledoc """
  # The RemoteResponse Object ### Description The `RemoteResponse` object is used to represent information returned from a third-party endpoint.  ### Usage Example View the `RemoteResponse` returned from your `DataPassthrough`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"model_name",
    :"model_id",
    :"last_sync_start",
    :"next_sync_start",
    :"status",
    :"is_initial_sync"
  ]

  @type t :: %__MODULE__{
    :"model_name" => String.t,
    :"model_id" => String.t,
    :"last_sync_start" => DateTime.t,
    :"next_sync_start" => DateTime.t,
    :"status" => String.t,
    :"is_initial_sync" => boolean()
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.SyncStatus do
  def decode(value, _options) do
    value
  end
end

