# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.Tag do
  @moduledoc """
  # The Tag Object ### Description The `Tag` object is used to represent a tag for a candidate.  ### Usage Example Fetch from the `LIST Tags` endpoint and view the tags used within a company.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"remote_id",
    :"name",
    :"remote_data"
  ]

  @type t :: %__MODULE__{
    :"remote_id" => String.t | nil,
    :"name" => String.t | nil,
    :"remote_data" => [RemoteData] | nil
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.Tag do
  def decode(value, _options) do
    value
  end
end

