# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Model.Url do
  @moduledoc """
  # The Url Object ### Description The `Url` object is used to represent a candidate's website.  ### Usage Example Fetch from the `GET Candidate` endpoint and view their website urls.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"value",
    :"url_type"
  ]

  @type t :: %__MODULE__{
    :"value" => String.t | nil,
    :"url_type" => UrlTypeEnum | nil
  }
end

defimpl Poison.Decoder, for: MergeATSClient.Model.Url do
  import MergeATSClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"url_type", :struct, MergeATSClient.Model.UrlTypeEnum, options)
  end
end

