# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Api.Interviews do
  @moduledoc """
  API calls for all endpoints tagged `Interviews`.
  """

  alias MergeATSClient.Connection
  import MergeATSClient.RequestBuilder


  @doc """
  Returns a list of `ScheduledInterview` objects.

  ## Parameters

  - connection (MergeATSClient.Connection): Connection to server
  - x_account_token (String.t): Token identifying the end user.
  - opts (KeywordList): [optional] Optional parameters
    - :application_id (String.t): If provided, will only return interviews for this application.
    - :created_after (DateTime.t): If provided, will only return objects created after this datetime.
    - :created_before (DateTime.t): If provided, will only return objects created before this datetime.
    - :cursor (String.t): The pagination cursor value.
    - :expand (String.t): Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
    - :modified_after (DateTime.t): If provided, will only return objects modified after this datetime.
    - :modified_before (DateTime.t): If provided, will only return objects modified before this datetime.
    - :organizer_id (String.t): If provided, will only return interviews organized by this user.
    - :page_size (integer()): Number of results to return per page.
    - :remote_id (String.t): The API provider's ID for the given object.
  ## Returns

  {:ok, %MergeATSClient.Model.PaginatedScheduledInterviewList{}} on success
  {:error, info} on failure
  """
  @spec interviews_list(Tesla.Env.client, String.t, keyword()) :: {:ok, MergeATSClient.Model.PaginatedScheduledInterviewList.t} | {:error, Tesla.Env.t}
  def interviews_list(connection, x_account_token, opts \\ []) do
    optional_params = %{
      :"application_id" => :query,
      :"created_after" => :query,
      :"created_before" => :query,
      :"cursor" => :query,
      :"expand" => :query,
      :"modified_after" => :query,
      :"modified_before" => :query,
      :"organizer_id" => :query,
      :"page_size" => :query,
      :"remote_id" => :query
    }
    %{}
    |> method(:get)
    |> url("/interviews")
    |> add_param(:headers, :"X-Account-Token", x_account_token)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %MergeATSClient.Model.PaginatedScheduledInterviewList{}}
    ])
  end

  @doc """
  Returns a `ScheduledInterview` object with the given `id`.

  ## Parameters

  - connection (MergeATSClient.Connection): Connection to server
  - x_account_token (String.t): Token identifying the end user.
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :expand (String.t): Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
  ## Returns

  {:ok, %MergeATSClient.Model.ScheduledInterview{}} on success
  {:error, info} on failure
  """
  @spec interviews_retrieve(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, MergeATSClient.Model.ScheduledInterview.t} | {:error, Tesla.Env.t}
  def interviews_retrieve(connection, x_account_token, id, opts \\ []) do
    optional_params = %{
      :"expand" => :query
    }
    %{}
    |> method(:get)
    |> url("/interviews/#{id}")
    |> add_param(:headers, :"X-Account-Token", x_account_token)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %MergeATSClient.Model.ScheduledInterview{}}
    ])
  end
end
