# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Api.LinkToken do
  @moduledoc """
  API calls for all endpoints tagged `LinkToken`.
  """

  alias MergeATSClient.Connection
  import MergeATSClient.RequestBuilder


  @doc """
  Creates a link token to be used when linking a new end user.

  ## Parameters

  - connection (MergeATSClient.Connection): Connection to server
  - end_user_details_request (EndUserDetailsRequest): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, MergeATSClient.Model.LinkToken.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec link_token_create(Tesla.Env.client, MergeATSClient.Model.EndUserDetailsRequest.t, keyword()) :: {:ok, MergeATSClient.Model.LinkToken.t} | {:error, Tesla.Env.t}
  def link_token_create(connection, end_user_details_request, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/link-token")
    |> add_param(:body, :body, end_user_details_request)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %MergeATSClient.Model.LinkToken{}}
    ])
  end
end
