# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSClient.Api.RegenerateKey do
  @moduledoc """
  API calls for all endpoints tagged `RegenerateKey`.
  """

  alias MergeATSClient.Connection
  import MergeATSClient.RequestBuilder


  @doc """
  Exchange remote keys.

  ## Parameters

  - connection (MergeATSClient.Connection): Connection to server
  - remote_key_for_regeneration_request (RemoteKeyForRegenerationRequest): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, %MergeATSClient.Model.RemoteKey{}} on success
  {:error, info} on failure
  """
  @spec regenerate_key_create(Tesla.Env.client, MergeATSClient.Model.RemoteKeyForRegenerationRequest.t, keyword()) :: {:ok, MergeATSClient.Model.RemoteKey.t} | {:error, Tesla.Env.t}
  def regenerate_key_create(connection, remote_key_for_regeneration_request, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/regenerate-key")
    |> add_param(:body, :body, remote_key_for_regeneration_request)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %MergeATSClient.Model.RemoteKey{}}
    ])
  end
end
