# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Mergee.Model.Eeoc do
  @moduledoc """
  # The EEOC Object ### Description The `EEOC` object is used to represent the Equal Employment Opportunity Commission information for a candidate.  ### Usage Example Fetch from the `LIST EEOCs` endpoint and filter by `candidate` to show all EEOC information for a candidate.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"candidate",
    :"submitted_at",
    :"race",
    :"gender",
    :"veteran_status",
    :"disability_status"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"candidate" => String.t | nil,
    :"submitted_at" => DateTime.t | nil,
    :"race" => RaceEnum | nil,
    :"gender" => GenderEnum | nil,
    :"veteran_status" => VeteranStatusEnum | nil,
    :"disability_status" => DisabilityStatusEnum | nil
  }
end

defimpl Poison.Decoder, for: Mergee.Model.Eeoc do
  import Mergee.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"race", :struct, Mergee.Model.RaceEnum, options)
    |> deserialize(:"gender", :struct, Mergee.Model.GenderEnum, options)
    |> deserialize(:"veteran_status", :struct, Mergee.Model.VeteranStatusEnum, options)
    |> deserialize(:"disability_status", :struct, Mergee.Model.DisabilityStatusEnum, options)
  end
end

