# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Mergee.Model.EmailAddress do
  @moduledoc """
  # The EmailAddress Object ### Description The `EmailAddress` object is used to represent a candidate's email address.  ### Usage Example Fetch from the `GET Candidate` endpoint and view their email addresses.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"value",
    :"email_address_type"
  ]

  @type t :: %__MODULE__{
    :"value" => String.t | nil,
    :"email_address_type" => EmailAddressTypeEnum | nil
  }
end

defimpl Poison.Decoder, for: Mergee.Model.EmailAddress do
  import Mergee.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"email_address_type", :struct, Mergee.Model.EmailAddressTypeEnum, options)
  end
end

