# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Mergee.Model.Job do
  @moduledoc """
  # The Job Object ### Description The `Job` object is used to represent a Location offering at a company.  ### Usage Example Fetch from the `LIST Jobs` endpoint and filter by `ID` to show all job postings.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"name",
    :"status",
    :"remote_created_at",
    :"remote_updated_at",
    :"confidential",
    :"departments",
    :"offices",
    :"hiring_managers"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"name" => String.t | nil,
    :"status" => JobStatusEnum | nil,
    :"remote_created_at" => DateTime.t | nil,
    :"remote_updated_at" => DateTime.t | nil,
    :"confidential" => boolean() | nil,
    :"departments" => [String.t] | nil,
    :"offices" => [String.t] | nil,
    :"hiring_managers" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: Mergee.Model.Job do
  import Mergee.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"status", :struct, Mergee.Model.JobStatusEnum, options)
  end
end

