# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Mergee.Model.PaginatedScorecardList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"next",
    :"previous",
    :"results"
  ]

  @type t :: %__MODULE__{
    :"next" => String.t | nil,
    :"previous" => String.t | nil,
    :"results" => [Scorecard] | nil
  }
end

defimpl Poison.Decoder, for: Mergee.Model.PaginatedScorecardList do
  import Mergee.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"results", :list, Mergee.Model.Scorecard, options)
  end
end

