# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Mergee.Model.ScheduledInterview do
  @moduledoc """
  # The ScheduledInterview Object ### Description The `ScheduledInterview` object is used to represent an interview  ### Usage Example Fetch from the `LIST ScheduledInterviews` endpoint and filter by `interviewers` to show all office locations.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"application",
    :"organizer",
    :"interviewers",
    :"location",
    :"start_at",
    :"end_at",
    :"remote_created_at",
    :"remote_updated_at",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"application" => String.t | nil,
    :"organizer" => String.t | nil,
    :"interviewers" => [String.t] | nil,
    :"location" => String.t | nil,
    :"start_at" => DateTime.t | nil,
    :"end_at" => DateTime.t | nil,
    :"remote_created_at" => DateTime.t | nil,
    :"remote_updated_at" => DateTime.t | nil,
    :"status" => ScheduledInterviewStatusEnum | nil
  }
end

defimpl Poison.Decoder, for: Mergee.Model.ScheduledInterview do
  import Mergee.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"status", :struct, Mergee.Model.ScheduledInterviewStatusEnum, options)
  end
end

