# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSAPI.Api.LinkToken do
  @moduledoc """
  API calls for all endpoints tagged `LinkToken`.
  """

  alias MergeATSAPI.Connection
  import MergeATSAPI.RequestBuilder


  @doc """
  Creates a link token to be used when linking a new end user.

  ## Parameters

  - connection (MergeATSAPI.Connection): Connection to server
  - end_user_details (EndUserDetails): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, %MergeATSAPI.Model.LinkToken{}} on success
  {:error, info} on failure
  """
  @spec link_token_create(Tesla.Env.client, MergeATSAPI.Model.EndUserDetails.t, keyword()) :: {:ok, MergeATSAPI.Model.LinkToken.t} | {:error, Tesla.Env.t}
  def link_token_create(connection, end_user_details, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/link-token")
    |> add_param(:body, :body, end_user_details)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %MergeATSAPI.Model.LinkToken{}}
    ])
  end
end
