# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSAPI.Model.Candidate do
  @moduledoc """
  # The Candidate Object ### Description The `Candidate` object is used to represent a Candidate for various positions.  ### Usage Example Fetch from the `LIST Candidates` endpoint and filter by `ID` to show all candidates.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"first_name",
    :"last_name",
    :"company",
    :"title",
    :"remote_created_at",
    :"remote_updated_at",
    :"last_interaction_at",
    :"is_private",
    :"can_email",
    :"locations",
    :"phone_numbers",
    :"email_addresses",
    :"urls",
    :"tags",
    :"applications",
    :"attachments"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"first_name" => String.t | nil,
    :"last_name" => String.t | nil,
    :"company" => String.t | nil,
    :"title" => String.t | nil,
    :"remote_created_at" => DateTime.t | nil,
    :"remote_updated_at" => DateTime.t | nil,
    :"last_interaction_at" => DateTime.t | nil,
    :"is_private" => boolean() | nil,
    :"can_email" => boolean() | nil,
    :"locations" => [String.t] | nil,
    :"phone_numbers" => [PhoneNumber] | nil,
    :"email_addresses" => [EmailAddress] | nil,
    :"urls" => [Url] | nil,
    :"tags" => [Tag] | nil,
    :"applications" => [String.t] | nil,
    :"attachments" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: MergeATSAPI.Model.Candidate do
  import MergeATSAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"phone_numbers", :list, MergeATSAPI.Model.PhoneNumber, options)
    |> deserialize(:"email_addresses", :list, MergeATSAPI.Model.EmailAddress, options)
    |> deserialize(:"urls", :list, MergeATSAPI.Model.Url, options)
    |> deserialize(:"tags", :list, MergeATSAPI.Model.Tag, options)
  end
end

