# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSAPI.Model.PaginatedTagList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"next",
    :"previous",
    :"results"
  ]

  @type t :: %__MODULE__{
    :"next" => String.t | nil,
    :"previous" => String.t | nil,
    :"results" => [Tag] | nil
  }
end

defimpl Poison.Decoder, for: MergeATSAPI.Model.PaginatedTagList do
  import MergeATSAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"results", :list, MergeATSAPI.Model.Tag, options)
  end
end

