# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeATSAPI.Model.RemoteUser do
  @moduledoc """
  # The RemoteUser Object ### Description The `RemoteUser` object is used to represent a third party user.  ### Usage Example Fetch from the `LIST RemoteUsers` endpoint to show all users for a third party.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"first_name",
    :"last_name",
    :"email",
    :"disabled",
    :"remote_created_at",
    :"access_role"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"first_name" => String.t | nil,
    :"last_name" => String.t | nil,
    :"email" => String.t | nil,
    :"disabled" => boolean() | nil,
    :"remote_created_at" => DateTime.t | nil,
    :"access_role" => AccessRoleEnum | nil
  }
end

defimpl Poison.Decoder, for: MergeATSAPI.Model.RemoteUser do
  import MergeATSAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"access_role", :struct, MergeATSAPI.Model.AccessRoleEnum, options)
  end
end

